### ISSUE TITLE
Improve error message in case of misidentification of dialect (ValueError: Can't decode base64)

### ISSUE THREAD

**Issue by israelst** [turicas/rows#218] opened 2017-03-30 21:42 UTC
When I run the code bellow, I got the error `ValueError: Can't decode base64` because rows use the first line to discover the csv dialect, but the text present at the following line breaks the expectation.

```python
import rows
from io import BytesIO


csv = BytesIO(b"""problematic_text,cool_number
,42
"Problematic text with commas, ""quotes"" and a cool number: 4,2", 84""")

table = rows.import_from_csv(csv)
print(list(table))
```

The problem is solved if you add the dialect explicitly:
```python 
table = rows.import_from_csv(csv, dialect='excel')
```
but would be very nice to have a error message that points us to the right direction, like talking about dialects or just by telling the row and field where error happened.

**Comment by elnuno** [comment] 2017-03-30 23:45
The issue is that `rows.plugins.plugin_csv.discover_dialect` defaults to Excel if it fails guessing the dialect (using `unicodecsv.Sniffer.sniff`), but here it mispredicts the dialect and tries to parse using that. If @turicas thinks it might be worth it, I can try to add something to handle this case (i.e., if it fails using the guessed dialect we might as well try with the default again) and improve the error message (i.e., when it fails, at least mention what dialect was in use and where the error came from).

**Comment by israelst** [comment] 2017-04-02 02:43
I'm not very into building more complexity in dialect guessing (297a99293785272eeb23769822a04c4e49de70bf), I would actually prefer to be required to explicitly inform the dialect instead. What do you guys think?

Besides, I think that the boundaries between field type guessing and dialect guessing doesn't look clear, but the error message format as in d20c90dddbf7143f19f33cb775f80a4841bd0343 is a very good step towards this separation.  :+1:

**Comment by turicas** [comment] 2017-09-11 03:12
@israelst, the code you've used here to describe the problem is working on the current develop (071a58db79ac5811ae0a1c138e219726cfa8efdf). Is there any corner case in which you can cause this kind of "wrong error message" scenario)? If not, I think we could close this issue and then I'll review #219 as an enhancement.

**Comment by israelst** [comment] 2017-09-15 19:53
:+1: , feel free to close it.

**Closed** 2017-09-15 22:36 UTC
