### ISSUE TITLE
Command line rows --help with OverflowError

### ISSUE THREAD

**Issue by occoder** [turicas/rows#308] opened 2019-02-19 02:43 UTC
Running on windows 10, 64-bit and trying to execute rows --help, but getting following exception log:
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\rows.exe\__main__.py", line 5, in <module>
  File "c:\program files\python37\lib\site-packages\rows\__init__.py", line 22, in <module>
    import rows.plugins as plugins
  File "c:\program files\python37\lib\site-packages\rows\plugins\__init__.py", line 20, in <module>
    from . import plugin_csv as csv  # NOQA
  File "c:\program files\python37\lib\site-packages\rows\plugins\plugin_csv.py", line 34, in <module>
    unicodecsv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by turicas** [comment] 2019-02-21 17:36
Duplicate of #306.

**Closed as completed by turicas** 2019-02-21 17:36 UTC
Labels: duplicate
