### ISSUE TITLE
Error on pip install rows

### ISSUE THREAD

**Issue by lucassimon** [turicas/rows#221] opened 2017-05-14 02:43 UTC
pip install rows
Collecting rows
  Downloading rows-0.3.1.tar.gz
Requirement already satisfied: six in /home/lucas/venvs/sismart/lib/python2.7/site-packages (from rows)
Requirement already satisfied: unicodecsv in /home/lucas/venvs/sismart/lib/python2.7/site-packages (from rows)
Building wheels for collected packages: rows
  Running setup.py bdist_wheel for rows ... error
  Complete output from command /home/lucas/venvs/sismart/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-B_GnPn/rows/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy24bRHpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-B_GnPn/rows/setup.py", line 79, in <module>
      'Topic :: Utilities',
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 46, in run
      self.build_packages()
    File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
      self.build_module(module, module_file, package)
    File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 65, in build_module
      package)
    File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
      "'package' must be a string (dot-separated), list, or tuple")
  TypeError: 'package' must be a string (dot-separated), list, or tuple
  
  ----------------------------------------
  Failed building wheel for rows
  Running setup.py clean for rows
Failed to build rows
Installing collected packages: rows
  Running setup.py install for rows ... error
    Complete output from command /home/lucas/venvs/sismart/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-B_GnPn/rows/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YOUoSl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/lucas/venvs/sismart/include/site/python2.7/rows:
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-B_GnPn/rows/setup.py", line 79, in <module>
        'Topic :: Utilities',
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 46, in run
        self.build_packages()
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 373, in build_packages
        self.build_module(module, module_file, package)
      File "/home/lucas/venvs/sismart/local/lib/python2.7/site-packages/setuptools/command/build_py.py", line 65, in build_module
        package)
      File "/usr/lib/python2.7/distutils/command/build_py.py", line 334, in build_module
        "'package' must be a string (dot-separated), list, or tuple")
    TypeError: 'package' must be a string (dot-separated), list, or tuple
    
    ----------------------------------------
Command "/home/lucas/venvs/sismart/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-B_GnPn/rows/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YOUoSl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/lucas/venvs/sismart/include/site/python2.7/rows" failed with error code 1 in /tmp/pip-build-B_GnPn/rows`
`

**Comment by humrochagf** [comment] 2017-09-21 20:49
i had this sabe issue at my project and solved by upgrading the version of distribute:
`pip install -U distribute`

**Comment by turicas** [comment] 2017-10-01 22:10
@lucassimon could you please check if the problem is still happening? I think it was fixed on db6b87018d830e8c5e6598dbe727e3bb9974082a, but would like to know from you.

**Closed** 2017-10-01 22:10 UTC
Labels: bug
