### ISSUE TITLE
Column without values is interpreted as bytes

### ISSUE THREAD

**Issue by fjsj** [turicas/rows#265] opened 2017-12-04 22:22 UTC
Thanks for this great tool @turicas!
I'm not sure if this is a bug or the expected behavior, but if you have an empty column in your CSV, it's parsed as bytes.

If you do...
```  
import io, rows

csv_text = '"ID",Topics\n"1",""\n"2",""'
t = rows.import_from_csv(BytesIO(csv_text.encode('utf-8')))
print(t[0])
```
...you get `Row(id=1, topics=b'')`, i.e., topics as bytes.

IMHO this behavior is error-prone for the end-user.

**Comment by turicas** [comment] 2017-12-09 00:07
Thanks for reporting the issue. :)
This is a duplicate of #234 - I'm closing this one and will post your comment there.

**Closed by turicas** 2017-12-09 00:07 UTC

**Comment by fjsj** [comment] 2017-12-09 01:36
Sounds good. Thanks!
