### ISSUE TITLE
Can't read column names starting with numbers

### ISSUE THREAD

**Issue by biancarosa** [turicas/rows#154] opened 2016-05-29 01:19 UTC
I tried to read a CSV with column names starting with numbers and had a problem.

I don't have the error right now, but I can copy here later if needed.

I can also try to take a look as soon as I have some time left, but I'm not sure when it'll happen :P

**Comment by turicas** [comment] 2016-05-29 03:26
@biancarosa, thanks for creating the issue!
Which version are you using?
As soon as I remember, I've fixed this problem (adding a "_" on the beginning of the column name) in the `develop` branch. Could you please install this version and test it out? If it works, I can release a new version on PyPI.
You can install it by executing:

    pip install git+https://github.com/turicas/rows.git

**Comment by turicas** [comment] 2016-07-11 06:31
@biancarosa: this issue is duplicate of #119. It was fixed in 844a6e5.

**Closed by turicas** 2016-07-11 06:31 UTC
